server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kpsharma996/spring-cloud-config-server
          search-paths:
            - 'config-store/*service'
